# SPDX-License-Identifier: MIT
# Copyright (c) 2026 netscope contributors
FROM rust:1.80-slim as builder

WORKDIR /usr/src/netscope
RUN apt-get update && apt-get install -y libpcap-dev protobuf-compiler pkg-config libssl-dev

COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
COPY tools ./tools
COPY fixtures ./fixtures

RUN cargo build -p netscope-server --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libpcap0.8 ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/netscope/target/release/netscope-server /usr/local/bin/netscope-server

EXPOSE 9443 9444 8080

ENTRYPOINT ["netscope-server"]
