// SPDX-License-Identifier: MIT
// Copyright (c) 2026 netscope contributors
//! The tiny RFC services that became DDoS weapons.
//!
//! Echo, Discard, Daytime, Quote of the Day, Chargen and Time were specified in
//! the early 1980s as debugging aids, back when every host on the network was
//! known and trusted. They are four RFCs of about two pages each, and every one
//! of them is still compiled into equipment shipping today.
//!
//! They are worth dissecting for one reason: the UDP variants are reflectors.
//! A single spoofed datagram to Chargen returns up to 512 bytes to whoever the
//! source address claimed to be (RFC 864 — the request's contents are ignored
//! entirely). Quote of the Day does much the same. An attacker sends small
//! packets from a forged address and the victim receives the amplified flood,
//! from a source that has no idea it is participating.
//!
//! So seeing these on a capture is itself the finding. Nothing legitimate has
//! used them in thirty years, and a host answering on UDP 19 from the public
//! internet is a reflector waiting to be used — usually a printer, a switch
//! management port, or an embedded stack with the services left on by default.
//!
//! One module rather than six, because the services are two lines each and the
//! interesting logic — which direction, and how much came back — is shared.

use std::net::IpAddr;

use crate::models::Protocol;

use super::DissectedResult;

/// Seconds between the Time protocol's 1900 epoch and the Unix epoch
/// (RFC 868 gives this constant explicitly).
const EPOCH_1900_TO_1970: u64 = 2_208_988_800;

/// Largest response Chargen and QOTD are specified to send.
const MAX_RESPONSE: usize = 512;

/// Assemble a result. The service port appearing as *source* means this is the
/// answer, which is the direction carrying the reflected volume.
fn result(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    protocol: Protocol,
    summary: String,
) -> DissectedResult {
    DissectedResult {
        src_addr: src_ip,
        dst_addr: dst_ip,
        src_port: Some(src_port),
        dst_port: Some(dst_port),
        protocol,
        summary,
    }
}

// Written out rather than generated by a macro: `every_protocol_is_produced_by
// _some_dissector` greps the sources for `Protocol::X`, and a macro would hide
// every one of these names from it — which is exactly the drift that test
// exists to catch.

pub fn dissect_echo(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_echo(src_port == 7, payload);
    result(src_ip, dst_ip, src_port, dst_port, Protocol::Echo, summary)
}

pub fn dissect_discard(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_discard(src_port == 9, payload);
    result(
        src_ip,
        dst_ip,
        src_port,
        dst_port,
        Protocol::Discard,
        summary,
    )
}

pub fn dissect_daytime(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_daytime(src_port == 13, payload);
    result(
        src_ip,
        dst_ip,
        src_port,
        dst_port,
        Protocol::Daytime,
        summary,
    )
}

pub fn dissect_qotd(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_qotd(src_port == 17, payload);
    result(src_ip, dst_ip, src_port, dst_port, Protocol::Qotd, summary)
}

pub fn dissect_chargen(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_chargen(src_port == 19, payload);
    result(
        src_ip,
        dst_ip,
        src_port,
        dst_port,
        Protocol::Chargen,
        summary,
    )
}

pub fn dissect_time(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_time(src_port == 37, payload);
    result(src_ip, dst_ip, src_port, dst_port, Protocol::Time, summary)
}

pub fn dissect_tcpmux(
    src_ip: Option<IpAddr>,
    dst_ip: Option<IpAddr>,
    src_port: u16,
    dst_port: u16,
    payload: &[u8],
) -> DissectedResult {
    let summary = describe_tcpmux(src_port == 1, payload);
    result(
        src_ip,
        dst_ip,
        src_port,
        dst_port,
        Protocol::Tcpmux,
        summary,
    )
}

/// Read a payload as text, for the services whose whole content is a string.
fn text(payload: &[u8]) -> Option<String> {
    let trimmed = payload
        .iter()
        .copied()
        .take_while(|&b| b != 0)
        .collect::<Vec<_>>();
    let s = String::from_utf8(trimmed).ok()?;
    let s = s.trim();
    (!s.is_empty()).then(|| super::truncate(s, 80))
}

fn describe_echo(is_response: bool, payload: &[u8]) -> String {
    if is_response {
        format!(
            "Echo reply — {} reflected back to the sender",
            super::bytes(payload.len() as u64)
        )
    } else {
        format!("Echo request — {}", super::bytes(payload.len() as u64))
    }
}

fn describe_discard(is_response: bool, payload: &[u8]) -> String {
    if is_response {
        // Discard is specified to send nothing, so a reply is remarkable.
        "Discard — a reply, which this service is not supposed to send".to_string()
    } else {
        format!(
            "Discard — {} thrown away",
            super::bytes(payload.len() as u64)
        )
    }
}

fn describe_daytime(is_response: bool, payload: &[u8]) -> String {
    match (is_response, text(payload)) {
        (true, Some(when)) => format!("Daytime reply — {when}"),
        (true, None) => format!("Daytime reply — {}", super::bytes(payload.len() as u64)),
        (false, _) => "Daytime request".to_string(),
    }
}

fn describe_qotd(is_response: bool, payload: &[u8]) -> String {
    match (is_response, text(payload)) {
        (true, Some(quote)) => format!(
            "QOTD reply — {} returned{}: {quote}",
            super::bytes(payload.len() as u64),
            amplification_note(payload.len())
        ),
        (true, None) => format!(
            "QOTD reply — {} returned",
            super::bytes(payload.len() as u64)
        ),
        (false, _) => "QOTD request".to_string(),
    }
}

fn describe_chargen(is_response: bool, payload: &[u8]) -> String {
    if is_response {
        format!(
            "Chargen reply — {} returned{}",
            super::bytes(payload.len() as u64),
            amplification_note(payload.len())
        )
    } else {
        // RFC 864: the contents of the request are ignored entirely, which is
        // exactly what makes a one-byte spoofed datagram worth sending.
        format!(
            "Chargen request — {}, whose contents are ignored",
            super::bytes(payload.len() as u64)
        )
    }
}

/// Flag a response large enough to be worth reflecting.
///
/// The response size is what is actually observable in one packet; the ratio
/// is not, because the request that provoked it is a different packet and may
/// never have been captured. Saying "N bytes returned" is the honest claim.
fn amplification_note(len: usize) -> &'static str {
    if len >= MAX_RESPONSE / 2 {
        " — a reflection vector at this size"
    } else {
        ""
    }
}

fn describe_time(is_response: bool, payload: &[u8]) -> String {
    if !is_response {
        return "Time request".to_string();
    }
    let Some(raw) = payload
        .get(..4)
        .map(|b| u32::from_be_bytes([b[0], b[1], b[2], b[3]]))
    else {
        return "Time reply (truncated)".to_string();
    };
    // The count starts in 1900, not 1970, so a naive read is off by 68 years.
    let Some(unix) = (raw as u64).checked_sub(EPOCH_1900_TO_1970) else {
        return format!("Time reply — {raw} (before 1970; clock is badly wrong)");
    };
    match chrono::DateTime::from_timestamp(unix as i64, 0) {
        Some(when) => format!("Time reply — {}", when.format("%Y-%m-%d %H:%M:%S UTC")),
        None => format!("Time reply — {raw}"),
    }
}

fn describe_tcpmux(is_response: bool, payload: &[u8]) -> String {
    match (is_response, text(payload)) {
        // The reply is a bare '+' or '-' followed by an optional message.
        (true, Some(reply)) => match reply.chars().next() {
            Some('+') => "TCPMUX — service accepted".to_string(),
            Some('-') => format!("TCPMUX — refused: {}", reply.trim_start_matches('-').trim()),
            _ => format!("TCPMUX reply — {reply}"),
        },
        (true, None) => "TCPMUX reply".to_string(),
        (false, Some(service)) => format!("TCPMUX — requesting '{service}'"),
        (false, None) => "TCPMUX request".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The reason this module exists: a small datagram provokes a large reply
    /// to whoever the source address claimed to be.
    #[test]
    fn chargen_reports_the_volume_it_returns() {
        let r = dissect_chargen(None, None, 19, 40000, &[b'A'; 512]);
        assert_eq!(r.protocol, Protocol::Chargen);
        assert!(r.summary.contains("512 bytes returned"), "{}", r.summary);
        assert!(r.summary.contains("reflection vector"), "{}", r.summary);
    }

    /// What makes it usable as a weapon is that the request is not even read,
    /// so one spoofed byte is enough.
    #[test]
    fn a_chargen_request_notes_that_its_contents_are_ignored() {
        let summary = describe_chargen(false, b"x");
        assert!(summary.contains("contents are ignored"), "{summary}");
    }

    /// Direction is what separates the reflected flood from the trigger, and
    /// it is read from which side holds the service port.
    #[test]
    fn the_direction_decides_which_side_is_reported() {
        // Service port as source: this is the reply.
        let reply = dissect_chargen(None, None, 19, 40000, &[b'A'; 400]);
        assert!(reply.summary.contains("reply"), "{}", reply.summary);
        // Service port as destination: this is the request.
        let request = dissect_chargen(None, None, 40000, 19, b"x");
        assert!(request.summary.contains("request"), "{}", request.summary);
    }

    /// A small reply is not worth flagging as a vector; overstating it would
    /// make the flag useless.
    #[test]
    fn a_small_reply_is_not_called_a_reflection_vector() {
        assert!(!describe_chargen(true, &[b'A'; 8]).contains("reflection vector"));
        assert!(describe_chargen(true, &[b'A'; 256]).contains("reflection vector"));
    }

    /// Time counts from 1900, so a naive read is off by sixty-eight years.
    #[test]
    fn the_time_reply_is_decoded_from_the_1900_epoch() {
        // RFC 868 states this value corresponds to 00:00 1 Jan 1970 GMT.
        let epoch = (EPOCH_1900_TO_1970 as u32).to_be_bytes();
        assert_eq!(
            describe_time(true, &epoch),
            "Time reply — 1970-01-01 00:00:00 UTC"
        );
        // And a value the RFC also gives: 1 Jan 1976.
        let y1976 = 2_398_291_200u32.to_be_bytes();
        assert!(describe_time(true, &y1976).contains("1976-01-01"));
    }

    /// A value below the 1900-to-1970 offset cannot be a Unix time at all, and
    /// must not silently wrap into a plausible-looking date.
    #[test]
    fn an_impossible_timestamp_is_reported_not_wrapped() {
        let summary = describe_time(true, &1000u32.to_be_bytes());
        assert!(summary.contains("clock is badly wrong"), "{summary}");
        assert!(summary.contains("1000"), "{summary}");
    }

    /// Daytime and QOTD carry their whole answer as text.
    #[test]
    fn the_text_services_report_what_they_returned() {
        assert_eq!(
            describe_daytime(true, b"Sunday, July 20, 2026 18:32:58-GMT\r\n"),
            "Daytime reply — Sunday, July 20, 2026 18:32:58-GMT"
        );
        assert!(describe_qotd(true, b"A rolling stone gathers no moss.\r\n")
            .contains("A rolling stone gathers no moss."));
    }

    /// Discard is specified to answer nothing, so an answer is the finding.
    #[test]
    fn a_reply_from_discard_is_called_out() {
        assert!(describe_discard(false, &[0u8; 64]).contains("thrown away"));
        assert!(describe_discard(true, &[0u8; 4]).contains("not supposed to send"));
    }

    /// Echo reflects at one-to-one, which is still a reflector.
    #[test]
    fn echo_reports_the_reflection() {
        assert!(describe_echo(true, &[0u8; 100]).contains("100 bytes reflected"));
        assert!(describe_echo(false, &[0u8; 100]).contains("Echo request"));
    }

    /// TCPMUX answers with a sign, and a refusal carries its reason.
    #[test]
    fn tcpmux_accepts_and_refuses_distinguishably() {
        assert_eq!(describe_tcpmux(true, b"+\r\n"), "TCPMUX — service accepted");
        assert_eq!(
            describe_tcpmux(true, b"-no such service\r\n"),
            "TCPMUX — refused: no such service"
        );
        assert_eq!(
            describe_tcpmux(false, b"finger\r\n"),
            "TCPMUX — requesting 'finger'"
        );
    }

    #[test]
    fn truncated_does_not_panic() {
        assert_eq!(describe_time(true, &[]), "Time reply (truncated)");
        assert_eq!(describe_time(true, &[0, 0, 1]), "Time reply (truncated)");
        assert_eq!(describe_time(false, &[]), "Time request");
        assert_eq!(describe_daytime(true, &[]), "Daytime reply — 0 bytes");
        assert_eq!(describe_tcpmux(false, &[]), "TCPMUX request");
        assert_eq!(
            describe_echo(true, &[]),
            "Echo reply — 0 bytes reflected back to the sender"
        );
        // Non-UTF8 content must not be reported as text.
        assert_eq!(
            describe_daytime(true, &[0xFF, 0xFE]),
            "Daytime reply — 2 bytes"
        );
    }
}
