// SPDX-License-Identifier: MIT
// Copyright (c) 2026 netscope contributors
#[cfg(not(target_arch = "wasm32"))]
pub mod ai_traffic;
pub mod api_server;
#[cfg(not(target_arch = "wasm32"))]
pub mod capture;
pub mod config;
pub mod crypto;
#[cfg(not(target_arch = "wasm32"))]
pub mod db;
pub mod discover;
pub mod dissectors;
pub mod fieldbus;
#[cfg(not(target_arch = "wasm32"))]
pub mod editcap;
pub mod education;
#[cfg(not(target_arch = "wasm32"))]
pub mod export;
pub mod expert;
pub mod filter;
pub mod firewall;
pub mod flows;
pub mod game_plugins;
pub mod industrial_edge;
#[cfg(not(target_arch = "wasm32"))]
pub mod forensics;
#[cfg(not(target_arch = "wasm32"))]
pub mod formats;
pub mod llm_analytics;
pub mod models;
pub mod names;
pub mod opc_ua_traffic;
pub mod pair_correlation;
#[cfg(not(target_arch = "wasm32"))]
pub mod pcapng;
pub mod pqc_analytics;
pub mod pqc_dashboard;
pub mod pqc_rules;
pub mod pqc_wizard;
pub mod pqc_handshake;
#[cfg(not(target_arch = "wasm32"))]
pub mod pipeline;
pub mod plugins;
#[cfg(not(target_arch = "wasm32"))]
pub mod registry;
pub mod remote;
#[cfg(not(target_arch = "wasm32"))]
pub mod rotate;
#[cfg(not(target_arch = "wasm32"))]
pub mod siem;
pub mod stats;
#[cfg(not(target_arch = "wasm32"))]
pub mod stream;
pub mod threat;
